### ISSUE TITLE
How do I add new terms? Custom terms?

### ISSUE THREAD

**Issue by dh--** [jpoehnelt/in-solidarity-bot#101]
I'd like to submit some new terms to the project.

I think I can figure out how to add default terms from reading the code. I'm not sure how to add .yml files though.

If it helps, I'd be happy to write or review documentation for this, but I think I'd need some help to figure out how. Maybe a pull request, or some very rough guidance?

**Comment by jpoehnelt** [comment]
I added links in a few places to rules.ts and created an issue template for new rules for those who do not want to implement.

**Comment by jpoehnelt** [comment]
The documentation has also been updated showing how to use rules sourced entirely from the specific repo or the .github repo in the organization.

**Comment by jpoehnelt** [comment]
Closing as it is possible to add custom terms in config.
