### ISSUE TITLE
False positives in longer words

### ISSUE THREAD

**Issue by martinthomson** [jpoehnelt/in-solidarity-bot#217]
The word "manageable" (and derivatives of) hits the "man" filter.  See [this](https://github.com/quicwg/wg-materials/pull/206/checks?check_run_id=2076476784) for example.

Many (another word that would hit this filter) words that are listed probably need to appear in their entirety to be considered problematic.  Consider using "\b" to match on word boundaries for those words.  That might reduce false positives.

**Comment by larseggert** [comment]
We're not using the default config, we're using https://github.com/quicwg/.github/blob/main/.github/in-solidarity.yml. (But the default config may have the same issue.)

**Comment by jpoehnelt** [comment]
Thanks for reporting. I added a feature request for a link to the source config in the check summary.
