### ISSUE TITLE
Install as YAML-based workflow?

### ISSUE THREAD

**Issue by larseggert** [jpoehnelt/in-solidarity-bot#271]
Would it be possible to enable this functionality by adding a YAML-based workflow to a repo, instead of needing to manually activate the bot for a repo?

The latter requires a manual step, while the former can be automated (we create and configure a lot of repos from scripts), and the manual step isn't scriptable.

**Comment by jpoehnelt** [comment]
Closing out in favor of using the GitHub API to manage installations. https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28
