### ISSUE TITLE
"Could not load configuration"

### ISSUE THREAD

**Issue by larseggert** [jpoehnelt/in-solidarity-bot#295]
I have suddenly started to get "Could not load configuration" errors from the bot, but they contain no information on what might be the cause?

See for example https://github.com/NTAP/rfc8312bis/pull/77/checks

**Comment by jpoehnelt** [comment]
```
Error: [@probot/octokit-plugin-config] Configuration could not be parsed from https://api.github.com/repos/NTAP/warpcore/contents/.github%2Fin-solidarity.yml (YAML is not an object)
    at getConfigFile (/usr/src/app/node_modules/@probot/octokit-plugin-config/dist-node/index.js:129:13)
```

**Comment by jpoehnelt** [comment]
It seems you are using an invalid config file in your github org.

**Comment by jpoehnelt** [comment]
Can read more about shared configs at https://probot.github.io/docs/best-practices/#store-configuration-in-the-repository

**Comment by larseggert** [comment]
Any chance to get more diagnostics about where the YAML is broken? yamllint likes it.

**Comment by jpoehnelt** [comment]
The configuration file is a single line string with a file path. While it might be valid yaml, it is not a [valid configuration file](https://github.com/jpoehnelt/in-solidarity-bot/blob/main/docs/README.md). If you are intending to extend a config file, see the link above on probot best practices for configuration.

**Comment by larseggert** [comment]
Hm, thanks for the explanation. The weird thing is that this used to work. (The "single line string with a file path" is a git symlink.)

**Comment by jpoehnelt** [comment]
Weird that that worked and then stopped. Would probably be somewhere upstream: https://github.com/probot/octokit-plugin-config/commits/main 🤔
