### ISSUE TITLE
Using _extends with .github repos

### ISSUE THREAD

**Issue by larseggert** [jpoehnelt/in-solidarity-bot#416]
I was hoping that it would be possible to use a `.github/in-solidarity.yml` file inside an organization-wide `.github` repository, to have bot settings consistently applied across an org. That org-wide config file would contain `_extends: ietf/terminology`, to pick up the configuration from https://github.com/ietf/terminology/blob/main/.github/in-solidarity.yml.

That seems to fail, however, with an error that I don't know what to do about:
```
configuration is invalid: [
{
"instancePath": "",
"schemaPath": "#/additionalProperties",
"keyword": "additionalProperties",
"params": {
"additionalProperty": "_extends"
},
"message": "must NOT have additional properties"
}
]
```
Is this supposed to work? Am I doing this wrong somehow?

**Comment by jpoehnelt** [comment]
I'm thinking this is a probot issue that doesn't get the extends from an org config? Seems like https://github.com/probot/probot/issues/1294 was never fully resolved for v10+ of probot.

**Comment by jpoehnelt** [comment]
Closing this as it is a bug in probot, now at https://github.com/probot/probot/issues/1660.

**Comment by Uzlopak** [comment]
Probot is shallow copying the configuration files. I opened a PR for deepmerging.

https://github.com/probot/octokit-plugin-config/pull/263
