### ISSUE TITLE
[Feature Request] Add support for i18n

### ISSUE THREAD

**Issue by ghost** [jpoehnelt/in-solidarity-bot#480]
**Is your feature request related to a problem? Please describe.**
As an international community, many developers write in human languages other than English, and they may want to make sure that they are writing code and documentation with inclusive language in their native language. For instance, many popular libraries and frameworks need help translating documentation, and if someone sees a community-translated docs page as non-inclusive, that will damage the public reputation of a community.
**Describe the solution you'd like**
I have a good idea for how to implement a rule-set fit for i18n. A better way to structure the rule-set is to structure it with the following type signature:

```ts
export type Rules = {
    lang: string, // example: 'es-MX'
    defaultMessage: string, // a mustache template
    rules: {
        regex: (string | RegExp)[],
        level: Level,
        alternatives?: string[],
        message?: string;
    }[]
}[]
```

A list of fallback locales could be exported to cover similar locales. The matching algorithm would use a similar process as the current matching algorithm.

Regarding configuration, a list of specific locales would need to be provided by the user somehow, so `In Solidarity` does not trigger a false-positive for a language the user is not looking for; after all, a combination of text in one language could set off a false alarm from a rule for a totally different language.

**Describe alternatives you've considered**
Sure, developers could provide several different rules in their own languages, but it could cause unexpected results.
**Additional context**
This idea was inspired by [`i18next.init({...})`](https://www.i18next.com/overview/configuration-options).

**Comment by jpoehnelt** [comment]
How is it determined which language should be used for which file?
