### ISSUE TITLE
App triggers on it's own configuration file

### ISSUE THREAD

**Issue by gauntface** [jpoehnelt/in-solidarity-bot#54]
I was adding the configuration file and received a warning on the config file itself. Ideally, this would ignore the config path.

![6wA62pNxx93o4LK](https://user-images.githubusercontent.com/139760/92285537-693a2480-eeb9-11ea-8414-7331b83f497b.png)

**Comment by gauntface** [comment]
Also not seeing any difference when adding a config. Am I setting it up wrong?

Config file is here: https://github.com/gauntface/test-solidarity/blob/master/.github/in-solidarity.yml
Example PR is here: https://github.com/gauntface/test-solidarity/pull/2

Thanks,
Matt

**Comment by jpoehnelt** [comment]
As to the second comment, Probot based apps [load config from the default branch](https://github.com/probot/probot/issues/561).
