### ISSUE TITLE
Improve the annotation message

### ISSUE THREAD

**Issue by jpoehnelt** [jpoehnelt/in-solidarity-bot#79]
The annotation messages could be improved with the contents of the line that caused the match. This will avoid having to go to each file to see the matches.

![Screenshot 2020-09-24 at 2 52 56 PM](https://user-images.githubusercontent.com/3392975/94199272-c94b3780-fe75-11ea-97c2-5b8f0c56f16f.png)

Perhaps:

> Match Found
> Please consider an alternative to `master` for the line containing `const master = '1234'`.

Annotation created at https://github.com/jpoehnelt/in-solidarity-bot/blob/main/src/annotate.ts#L61.

Additional reference:  https://docs.github.com/en/rest/reference/checks#annotations-items.

**Comment by Apoorve73** [comment]
Can you please brief the exact issue?

**Comment by jpoehnelt** [comment]
Updated the issue.

**Comment by Apoorve73** [comment]
I would like to work on this issue. It will be great, if you can share, how to run the project. I have worked with React JS using npm, so it won't be much different, I guess.

**Comment by jpoehnelt** [comment]
@Apoorve73 

It should be fairly straightforward to run and test.

1. `npm i`
1. make changes
1. make changes to tests
1. `npm test`
1. `npm run lint` fix some issues with `npm run format`

Let me know if you have any questions.

**Comment by Apoorve73** [comment]
Thank you @jpoehnelt ! I will adda comment, if face any problem.
