### ISSUE TITLE
Allow configuration for an entire org

### ISSUE THREAD

**Issue by lesv** [jpoehnelt/in-solidarity-bot#97]
Some orgs, like: [GoogleAPIs](https://github.com/GoogleAPIs/.github) & [Google](https://github.com/Google/.github) have a `.github` root repo for default configuration.  It would be nice if in-solidarity-bot allowed configuration at the org level in addition to the repo level.

It would also be nice if it allowed configuration of wordlists and alternative suggestion.

**Comment by jpoehnelt** [comment]
It already supports config at the org level as this is built-in to probot. See the probot [best practices](https://github.com/probot/probot/blob/master/docs/best-practices.md#store-configuration-in-the-repository) for more on this.

**Comment by jpoehnelt** [comment]
I added support for custom rules in #98.
